export const GRANJAS: string[] = [
  'SISALLAR 1',
  'CARTUJA 1',
  'NOVIPORC',
  'LA INDUSTRIAL',
  'LA MASIA',
  'CARTUJA 2',
  'FUSTERO',
  'PORDECONA',
  'LA GUINEU',
  'MARRUGAT',
  'FAYON ABUELAS',
  'ZAIDIN',
  'SISALLAR 3',
  'RAMONILLO',
  'EL SOLER',
  'CASTELLNOU',
  'PASCUALET',
  'SANTAROSA',
  'MAIALS',
  'S25',
  'LANAJA 2',
  'ALFUSPI',
  'MASSOS',
  'PORDALL',
  'GRANADELLA',
  'SISALLAR 4',
  'EL PI',
  'COFITA',
  'LANAJA 5',
  'PEÑALBA 1',
  'LANAJA 4',
  'OLIOLA',
  'CASERIO',
  'PORCELIBOR',
  'CAMPORRELLS',
  'ONTIÑENA',
  'ARIESTOLAS',
  'LANAJA 1',
  'FAYON 2',
  'PEÑALBA 2',
  'LANAJA 6',
  'SINOGA',
  'CARCUM',
  'JAUMEANDREU',
  'FAYON 1',
  'RENANT',
  'LES SERRES',
  'LANAJA 3',
  'URMA',
  'LECIÑENA',
  'FAYON 3',
  'ARESTE',
  'BORGES',
]

export type Estado = 'verde' | 'amarillo' | 'rojo'

export const ESTADO_COLORS: Record<Estado, string> = {
  verde: '#22c55e',
  amarillo: '#eab308',
  rojo: '#ef4444',
}

export const NEXT_ESTADO: Record<Estado, Estado> = {
  verde: 'amarillo',
  amarillo: 'rojo',
  rojo: 'verde',
}
